name: Build-Documentation

on: [push, pull_request]

# Make sure we don't have more than one active workflow to prevent race conditions
# e.g a previous build may update docs later and overwrite if we don't have this.
# It is ok to have parallel runs for push and PR events and from different branches.
# We can cancel previous runs for non-trunk events.
concurrency:
  group: build-documentation-${{ github.ref }}-${{ github.event_name }}

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Using a shallow checkout. Change to `0` if a full fetch is required.

      - name: Set variables
        id: vars
        run: |
          echo "default_ref=${{ format('refs/heads/{0}', github.event.repository.default_branch) }}" >> $GITHUB_OUTPUT

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          doxyfile-path: 'doxygen-public.conf'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == steps.vars.outputs.default_ref }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          enable_jekyll: true
